import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import firebase from '../firebase/index';

import { TextField } from '@mui/material';

export default function Home() {
  const router = useRouter();
  const [isUser, setIsUser] = useState(false);
  const [fullName, setFullName] = useState("");
  const [number, setNumber] = useState("");
  const [currUID, setCurrUID] = useState("");

  useEffect(() => {
    firebase().auth.onAuthStateChanged((user) => {
      if (user) {
        setCurrUID(user.uid);
        setIsUser(true);
        console.log(user.uid);
      } else {

        console.log("not a user");
      }
    });
  }, [])

  const uiDispatcher = () => {
      if (isUser) {
        return (
          <> 
              <TextField 
                id = 't1'
                label = 'full name'
                variant = 'outlined'
                onChange = {(e) => setFullName(e.target.value)}
              /> 
              

              <TextField 
                id = 't2'
                label = 'number'
                variant = 'outlined'
                onChange = {(event) => {
                    setNumber(event.target.value);
                }}
              /> 


              <button 
                style={{padding: 20}} 
                title={isUser ? 'Logout' : 'Create Details'} 
                onClick = {async () => {
                  if (fullName !== "" && number !== "") {
                    const {db, ref, set} = firebase();
                    await set(ref(db, "users/" + currUID), {
                      fullName : fullName,
                      mobile: number,
                      uid: currUID
                    })
                  } else {
                    alert("fill up the form please!")
                  }
              }}>
                <h1> Create Details </h1>
              </button>
          </>
        )
      }

      return null;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <button 
          style={{padding: 20}} 
          title={isUser ? 'Logout' : 'Create Details'} 
          onClick = {() => {
            if (isUser) {
                firebase().auth.signOut();
                setIsUser(false);
            } else {
              router.push("/dashboard");
            }
        }}>
          <h1> {isUser ? 'Logout' : 'Create User'} </h1>
        </button>

        {uiDispatcher()}

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
