import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import firebase from '../../firebase/index';
import { TextField } from '@mui/material';

// 3:11:50 in training video
// test
export default function Dashboard() {
  const router = useRouter();
  const [email, setEmail]= useState("");
  const [password, setPassword] = useState("");
  
  const uiDispatcher = () => {};
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to User Screen
        </h1>

        <TextField 
          id = 't1'
          label = 'email address'
          variant = 'outlined'
          onChange = {(e) => setEmail(e.target.value)}
        /> 
        

        <TextField 
          id = 't2'
          label = 'password'
          variant = 'outlined'
          onChange = {(event) => {
              setPassword(event.target.value);
          }}
        /> 

        <button style={{padding: 20}} onClick = {async () => {
            const firebaseAuth = firebase().auth;
            await firebase()
                  .createUserWithEmailAndPassword(firebaseAuth, email, password)
                  .catch((e) => console.log({e}));

            router.push("/");
        }}>
            <h1>Create User</h1>
        </button>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
